services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./app/.env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_SUPABASE_URL=http://host.docker.internal:54321
